# Generated by Django 5.0.6 on 2024-06-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntariodb',
            name='correo',
            field=models.TextField(max_length=30, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='voluntariodb',
            name='tlf',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
