# Generated by Django 5.0.6 on 2024-06-21 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_user_remove_perrosdb_fk_est_remove_perrosdb_fk_gen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esterilizaciondb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est', models.CharField(max_length=20, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Estelirizacion',
                'db_table': 'Esterilizacion',
            },
        ),
        migrations.CreateModel(
            name='Generodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.CharField(max_length=20, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Generos',
                'db_table': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Tamañodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(max_length=20, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Tamaños',
                'db_table': 'Tamaño',
            },
        ),
        migrations.CreateModel(
            name='Voluntariodb',
            fields=[
                ('ced', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('ape', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('tlf', models.IntegerField(verbose_name='Telefono')),
                ('correo', models.TextField(max_length=30, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
                'db_table': 'Voluntarios',
            },
        ),
        migrations.CreateModel(
            name='Perrosdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, verbose_name='Nombre')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('desc', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('raza', models.CharField(max_length=30, verbose_name='Raza')),
                ('fk_est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.esterilizaciondb')),
                ('fk_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.generodb')),
                ('fk_tam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tamañodb')),
            ],
            options={
                'verbose_name': 'Perro',
                'verbose_name_plural': 'Perros',
                'db_table': 'Perros',
            },
        ),
    ]
