# Generated by Django 5.0.6 on 2024-06-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_rename_voluntariodb_adoptantedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrosdb',
            name='photo',
            field=models.ImageField(default='Perro_default.jpg', upload_to='Perros/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='User_default.jpg', upload_to='Users/'),
        ),
    ]
