# Generated by Django 5.0.6 on 2024-06-21 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_perrosdb_photo_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrosdb',
            name='fk_est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.esterilizaciondb', verbose_name='Estelirizacion'),
        ),
        migrations.AlterField(
            model_name='perrosdb',
            name='fk_gen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.generodb', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='perrosdb',
            name='fk_tam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tamañodb', verbose_name='Tamaño'),
        ),
    ]
