# Generated by Django 5.0.6 on 2024-06-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_alter_perrosdb_fk_est_alter_perrosdb_fk_gen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptantedb',
            name='photo',
            field=models.ImageField(default='Adoptante_default.jpg', upload_to='Adoptante/'),
        ),
    ]
