# Generated by Django 5.0.6 on 2024-06-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_adoptantedb_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptantedb',
            name='ced',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Cedula'),
        ),
    ]
