# Generated by Django 5.0.6 on 2024-06-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_alter_adoptantedb_ced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptantedb',
            name='ape',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='adoptantedb',
            name='correo',
            field=models.TextField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='adoptantedb',
            name='tlf',
            field=models.CharField(max_length=100, verbose_name='Telefono'),
        ),
    ]
