# Generated by Django 5.0.6 on 2024-06-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_alter_adoptantedb_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptantedb',
            options={'verbose_name': 'Adoptante', 'verbose_name_plural': 'Adoptantes'},
        ),
        migrations.AlterModelTable(
            name='adoptantedb',
            table='Adoptantes',
        ),
    ]
