# Generated by Django 5.0.6 on 2024-06-21 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_alter_adoptantedb_options_alter_adoptantedb_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, verbose_name='Nombre')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('desc', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('raza', models.CharField(max_length=30, verbose_name='Raza')),
                ('photo', models.ImageField(default='Gato_default.jpg', upload_to='Gatos/')),
                ('fk_est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.esterilizaciondb', verbose_name='Estelirizacion')),
                ('fk_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.generodb', verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Gato',
                'verbose_name_plural': 'Gatos',
                'db_table': 'Gatos',
            },
        ),
    ]
