# Generated by Django 5.0.6 on 2024-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_gatodb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatodb',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perrosdb',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
