# Generated by Django 5.0.6 on 2024-06-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_vacunas_perrodb'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunas_perrodb',
            name='vac1',
            field=models.CharField(default=None, max_length=50, verbose_name='Vacuna 1'),
        ),
    ]
