# Generated by Django 5.0.6 on 2024-06-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_vacunas_perrodb_vac1'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunas_perrodb',
            name='vac2',
            field=models.CharField(default=None, max_length=50, verbose_name='Vacuna 2'),
        ),
        migrations.AddField(
            model_name='vacunas_perrodb',
            name='vac3',
            field=models.CharField(default=None, max_length=50, verbose_name='Vacuna 3'),
        ),
    ]
