# Generated by Django 5.0.6 on 2024-06-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0019_perrosdb_obs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacunas_perrodb',
            options={'verbose_name': 'Vacunas Perros'},
        ),
        migrations.CreateModel(
            name='vacunas_gatodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac1', models.CharField(default=None, max_length=50, verbose_name='Parvovirus')),
                ('vac2', models.CharField(default=None, max_length=50, verbose_name='Vacuna 2')),
                ('vac3', models.CharField(default=None, max_length=50, verbose_name='Vacuna 3')),
                ('fk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.gatodb', verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Vacunas Gatos',
                'db_table': 'Vacunas_Gatos',
            },
        ),
    ]
