# Generated by Django 5.0.6 on 2024-06-21 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0022_alter_vacunas_gatodb_vac1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resguardodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.perrosdb', verbose_name='Animal')),
                ('Cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuidador')),
            ],
        ),
    ]
