# Generated by Django 5.0.6 on 2024-06-21 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0024_resguardo_perrodb_delete_resguardodb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resguardo_gatodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuidador')),
                ('Gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.gatodb', verbose_name='Perro')),
            ],
        ),
    ]
