# Generated by Django 5.0.6 on 2024-06-22 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0025_resguardo_gatodb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especiedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=20, verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Especie',
                'db_table': 'Especie',
            },
        ),
        migrations.RemoveField(
            model_name='resguardo_gatodb',
            name='Gato',
        ),
        migrations.RemoveField(
            model_name='vacunas_gatodb',
            name='fk_id',
        ),
        migrations.RemoveField(
            model_name='perrosdb',
            name='fk_est',
        ),
        migrations.RemoveField(
            model_name='perrosdb',
            name='fk_gen',
        ),
        migrations.RemoveField(
            model_name='perrosdb',
            name='fk_tam',
        ),
        migrations.RemoveField(
            model_name='resguardo_perrodb',
            name='Perro',
        ),
        migrations.RemoveField(
            model_name='vacunas_perrodb',
            name='fk_id',
        ),
        migrations.RemoveField(
            model_name='resguardo_gatodb',
            name='Cuidador',
        ),
        migrations.RemoveField(
            model_name='resguardo_perrodb',
            name='Cuidador',
        ),
        migrations.CreateModel(
            name='Animalesdb',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, verbose_name='Nombre')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('desc', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('obs', models.TextField(max_length=500, verbose_name='Observaciones')),
                ('raza', models.CharField(max_length=30, verbose_name='Raza')),
                ('photo', models.ImageField(default='Animal_default.jpg', upload_to='Animal/')),
                ('fk_est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.esterilizaciondb', verbose_name='Estelirizacion')),
                ('fk_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.generodb', verbose_name='Genero')),
                ('fk_tam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tamañodb', verbose_name='Tamaño')),
                ('fk_esp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APP.especiedb', verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'db_table': 'Animal',
            },
        ),
        migrations.CreateModel(
            name='Resguardodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuidador')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.animalesdb', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Resguardo Perro',
                'verbose_name_plural': 'Resguardo Perros',
                'db_table': 'Resguardo Perros',
            },
        ),
        migrations.CreateModel(
            name='Adopcionesdb',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id')),
                ('Fecha', models.DateField(verbose_name='Fecha de adopcion')),
                ('Adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.adoptantedb')),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.resguardodb', verbose_name='Cuidador')),
            ],
            options={
                'verbose_name': 'Adopciones',
                'db_table': 'Adopciones',
            },
        ),
        migrations.DeleteModel(
            name='Gatodb',
        ),
        migrations.DeleteModel(
            name='vacunas_gatodb',
        ),
        migrations.DeleteModel(
            name='Perrosdb',
        ),
        migrations.DeleteModel(
            name='vacunas_perrodb',
        ),
        migrations.DeleteModel(
            name='Resguardo_gatodb',
        ),
        migrations.DeleteModel(
            name='Resguardo_perrodb',
        ),
    ]
