# Generated by Django 5.0.6 on 2024-06-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0027_rename_especiedb_especiesdb_alter_animalesdb_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especiesdb',
            new_name='Tipodb',
        ),
        migrations.AlterModelOptions(
            name='tipodb',
            options={'verbose_name': 'Tipos'},
        ),
        migrations.AlterModelTable(
            name='tipodb',
            table='Tipo',
        ),
    ]
