# Generated by Django 5.0.6 on 2024-06-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0028_rename_especiesdb_tipodb_alter_tipodb_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodb',
            options={},
        ),
        migrations.AlterModelTable(
            name='tipodb',
            table=None,
        ),
    ]
