# Generated by Django 5.0.6 on 2024-06-22 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0029_alter_tipodb_options_alter_tipodb_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adopcionesdb',
            options={'verbose_name': 'Adopciones', 'verbose_name_plural': 'Adopciones'},
        ),
        migrations.AlterModelOptions(
            name='tipodb',
            options={'verbose_name': 'Tipos', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterModelTable(
            name='tipodb',
            table='Tipo',
        ),
    ]
