# Generated by Django 5.0.6 on 2024-06-22 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0030_alter_adopcionesdb_options_alter_tipodb_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcionesdb',
            name='Animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.resguardodb', verbose_name='Mascota'),
        ),
    ]
