# Generated by Django 5.0.6 on 2024-06-22 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0032_alter_adopcionesdb_animal_alter_resguardodb_cuidador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Adb',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id')),
                ('fk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.adopcionesdb')),
            ],
            options={
                'verbose_name': 'Historial de adopciones',
                'db_table': 'Historial_Adopciones',
            },
        ),
        migrations.CreateModel(
            name='Historial_Fdb',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id')),
                ('fk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.fallecimientodb')),
            ],
            options={
                'verbose_name': 'Historial de Fallecimiento',
                'db_table': 'Historial_Fallecimiento',
            },
        ),
    ]
