# Generated by Django 5.0.6 on 2024-07-10 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0033_historial_adb_historial_fdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resguardodb',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.animalesdb', verbose_name='Mascota'),
        ),
    ]
