# Generated by Django 5.0.6 on 2024-07-11 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0034_alter_resguardodb_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotadb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.CharField(max_length=60, verbose_name='Nombre')),
                ('edad', models.IntegerField(verbose_name='Edad')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'Mascotas',
            },
        ),
        migrations.AlterField(
            model_name='animalesdb',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='resguardodb',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.mascotadb', verbose_name='Mascota'),
        ),
    ]
