# Generated by Django 5.0.6 on 2024-07-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0035_mascotadb_alter_animalesdb_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotadb',
            name='estado',
            field=models.CharField(default=5, max_length=50, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
