# Generated by Django 5.0.6 on 2024-07-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0037_alter_resguardodb_mascota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascotadb',
        ),
    ]
