# Generated by Django 5.0.6 on 2024-08-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0038_delete_mascotadb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial_fdb',
            name='fk_id',
        ),
        migrations.RemoveField(
            model_name='historial_adb',
            name='fk_id',
        ),
        migrations.RemoveField(
            model_name='adoptantedb',
            name='correo',
        ),
        migrations.DeleteModel(
            name='Fallecimientodb',
        ),
        migrations.DeleteModel(
            name='Historial_Fdb',
        ),
        migrations.DeleteModel(
            name='Historial_Adb',
        ),
    ]
