# Generated by Django 5.0.6 on 2024-09-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0040_remove_animalesdb_desc_alter_animalesdb_edad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tamañodb',
            options={'verbose_name': 'Tamaño'},
        ),
        migrations.RemoveField(
            model_name='animalesdb',
            name='obs',
        ),
        migrations.AddField(
            model_name='animalesdb',
            name='status',
            field=models.BooleanField(default=None, verbose_name='Status_adopcion'),
        ),
    ]
